server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  
  websocket:
    allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"

meshiya:
  diner:
    max-seats: 8
    ai-response-delay: 3000
    max-context-messages: 20

# AI Configuration
ai:
  # Provider: ollama, openai, anthropic
  provider: ollama
  
  # Ollama Configuration
  ollama:
    url: http://localhost:11434
    model: qwen3:4b
  
  # OpenAI Configuration (set api-key in environment or here)
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: gpt-3.5-turbo
  
  # Anthropic Configuration (set api-key in environment or here)
  anthropic:
    api-key: ${ANTHROPIC_API_KEY:}
    model: claude-3-haiku-20240307
  
  # Request timeout in milliseconds
  timeout: 30000